services:
  whitelabel-wiki:
    image: jcivitell/whitelable_wiki
    build:
      context: .
      dockerfile: ./Dockerfile
      tags:
      - "jcivitell/whitelable_wiki:${CIRCLE_BRANCH:-nobranch}"
      - "jcivitell/whitelable_wiki:${CIRCLE_TAG:-notag}"