services:
  whitelabel-wiki:
    image: jcivitell/whitelabel_wiki
    build:
      context: .
      dockerfile: ./Dockerfile
      tags:
      - "jcivitell/whitelabel_wiki:${CIRCLE_BRANCH:-nobranch}"
      - "jcivitell/whitelabel_wiki:${CIRCLE_TAG:-notag}"