# Generated by Django 5.0.1 on 2024-01-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wikibackend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="primary_color",
            field=models.CharField(default="FFFFFF", max_length=6),
        ),
        migrations.AddField(
            model_name="customer",
            name="secondary_color",
            field=models.CharField(default="000000", max_length=6),
        ),
    ]
